/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "nangu",
  "description": "nangu",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-988db186",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/UI/row.html",
      "relativePath": "UI/row.md",
      "key": "v-9be10cce",
      "path": "/UI/row.html"
    },
    {
      "title": "Api",
      "frontmatter": {},
      "regularPath": "/api.html",
      "relativePath": "api.md",
      "key": "v-43fe37be",
      "path": "/api.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "指南",
        "link": "/guide/"
      },
      {
        "text": "生活",
        "link": "/life/"
      },
      {
        "text": "学习",
        "items": [
          {
            "text": "英语",
            "link": "/study/english/english01"
          },
          {
            "text": "数学",
            "link": "/study/math/math01"
          }
        ]
      }
    ],
    "sidebar": {
      "/": [
        {
          "title": "UI",
          "collapsable": false,
          "children": [
            {
              "title": "布局",
              "path": "/UI/row"
            }
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated"
  }
}